import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useState, useEffect, useRef } from "react";
import useAccelerometer from "../hooks/useAccelerometer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const { x, y, z } = useAccelerometer();
  const [permissionGranted, setPermissionGranted] = useState(false);

  const xValues = useRef([]);
  const yValues = useRef([]);
  const zValues = useRef([]);
  const maxValues = 20;

  const [smoothX, setSmoothX] = useState(0);
  const [smoothY, setSmoothY] = useState(0);
  const [smoothZ, setSmoothZ] = useState(0);

  const requestMotionPermission = async () => {
    if (typeof DeviceMotionEvent.requestPermission === "function") {
      try {
        const permission = await DeviceMotionEvent.requestPermission();
        if (permission === "granted") {
          setPermissionGranted(true);
        } else {
          console.log("Permission denied");
        }
      } catch (error) {
        console.error("Permission request error", error);
      }
    }
  };

  useEffect(() => {
    if (typeof DeviceMotionEvent.requestPermission === "function") {
      requestMotionPermission();
    }
  }, []);

  useEffect(() => {
    if (x !== null && y !== null && z !== null) {
      xValues.current.push(x);
      yValues.current.push(y);
      zValues.current.push(z);

      if (xValues.current.length > maxValues) xValues.current.shift();
      if (yValues.current.length > maxValues) yValues.current.shift();
      if (zValues.current.length > maxValues) zValues.current.shift();

      setSmoothX(
        xValues.current.reduce((a, b) => a + b, 0) / xValues.current.length
      );
      setSmoothY(
        yValues.current.reduce((a, b) => a + b, 0) / yValues.current.length
      );
      setSmoothZ(
        zValues.current.reduce((a, b) => a + b, 0) / zValues.current.length
      );
    }
  }, [x, y, z]);

  return (
    <>
      <Head>
        <title>Accéléromètre App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="https://nextjs.org/icons/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />

          {!permissionGranted && (
            <button
              onClick={requestMotionPermission}
              className={styles.primary}
            >
              Autoriser l'accès aux capteurs
            </button>
          )}

          {permissionGranted && (
            <div>
              <h1>Accéléromètre iPhone</h1>
              <p>
                Accélération X: {smoothX ? smoothX.toFixed(2) : "En attente..."}
              </p>
              <p>
                Accélération Y: {smoothY ? smoothY.toFixed(2) : "En attente..."}
              </p>
              <p>
                Accélération Z: {smoothZ ? smoothZ.toFixed(2) : "En attente..."}
              </p>
            </div>
          )}
        </main>
      </div>
    </>
  );
}
